export { default as AppContainer } from './app.container';
export * from './app.container';
export * from './app.module';
export * from './app.service';
export * from './color';
export * from './config';
export * from './main';
export * from './material-color-utilities';
export * from './plugin';
export * from './plugins/font';
export * from './plugins/tailwind';
export * from './theme';
